### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MichaelJCole**
Adding links to examples and usage.

### CODE REVIEW

**Comment by atassis** [comment]
This repo offers a different way to connect, query, etc, examples are too different. Also, I don't want to make links to an older not supported repo, which is also disorienting users with bloats of repositories. Later this repo will become an official one when all documentation changes would be set. Do you have any better reasons than above to add these links?

**Comment by MichaelJCole** [comment]
Hi there, thanks for this great software.

"drop-in replacement" means the examples should work the same.

I was looking for how to use the driver.  Are there better examples or documentation?  I'm new to RethinkDB and hoping it's an alternative to Mongo.

Thank you!

**Comment by atassis** [comment]
First, I may advise you to join the slack server and ask for some help there
I'll try to write some proper examples in this repo, but they won't come that soon, I do [this](https://github.com/rethinkdb/rethinkdb-admin) now in my spare time.
You can help me by creating an issue with even a brief description of examples you want to see. The more you write- the wider explanation you get=)

**Comment by MichaelJCole** [comment]
Hi, I love the admin, thank you!

I started with the tests and made a small prototype.  I'll submit a PR
with it once it's done.

Thanks!

**Pull request closed without merging**
