### PR TITLE
Revert recent `cursor.ts` changes in favor of renaming the `closed` a property

### PR DESCRIPTION
**Pull request by dominykas**
**Reason for the change**

Fixes https://github.com/rethinkdb/rethinkdb-ts/issues/108

**Checklist**
- [x] I have read and agreed to the [RethinkDB Contributor License Agreement](http://rethinkdb.com/community/cla/)

### CODE REVIEW

**Comment by atassis** [comment]
Sorry, I was sick for a good period of time, will review this during this week. Thanks in advance!

**Review by atassis — APPROVED** [review]

**Comment by atassis** [comment]
Tested locally, soon will publish a fix. Thanks for a work!

**Comment by atassis** [comment]
Version `2.5.1` is published

**Comment by dominykas** [comment]
:bow:

**Pull request merged**
